stages:
  - install
  - test
  - build

# Install dependencies
install_dependencies:
  stage: install
  image: node:16
  script:
    - cd frontend
    - npm install  # Install dependencies, including Jest
  cache:
    paths:
      - frontend/node_modules/  # Cache the node_modules directory

# Run tests and generate coverage report
run_tests:
  stage: test
  image: node:16
  script:
    - cd frontend
    - npm test -- --ci --silent --coverage  # Run tests with coverage
  coverage: '/^Test Suites: \d+ passed, \d+ failed, \d+ total \(\d+% covered\)$/'
  artifacts:
    paths:
      - frontend/coverage
    expire_in: 1 hour  # Optional: set an expiration for artifacts

# Build the project
build_project:
  stage: build
  image: node:16
  script:
    - cd frontend
    - npm run build
  artifacts:
    paths:
      - frontend/build