stages:
  - install
  - test
  - build

install_dependencies:
  stage: install
  image: node:16
  script:
    - cd frontend
    - npm install  # Install all dependencies
  cache:
    key: npm-cache  # Unique cache key to reuse across jobs
    paths:
      - frontend/node_modules/  # Cache node_modules for later jobs

run_tests:
  stage: test
  image: node:16
  script:
    - cd frontend
    - npm test -- --ci --silent --coverage  # Now Jest should be available
  cache:
    key: npm-cache  # Use the same cache to ensure node_modules is available

# Build the project
build_project:
  stage: build
  image: node:16
  script:
    - cd frontend
    - npm run build
  artifacts:
    paths:
      - frontend/build